version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: test
    networks:
      - external_network
      - internal_network
    volumes:
      - .:/usr/src/drone-exercise
    depends_on:
      - db

  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - internal_network
    expose:
      - '3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

networks:
  external_network:
  internal_network:
    internal: true
